# Generated by Django 3.1 on 2020-10-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_seoobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoobject',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
