# Generated by Django 3.1 on 2020-10-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0003_auto_20201018_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoobject',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
