# Generated by Django 3.1 on 2020-10-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0004_auto_20201018_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seoobject',
            name='is_default',
        ),
        migrations.AddField(
            model_name='seoobject',
            name='keywords',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='seoobject',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
