# Generated by Django 3.1 on 2020-09-02 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('my_picture', models.ImageField(blank=True, upload_to='portfolio/website/')),
                ('description', models.CharField(max_length=120)),
                ('about_me', models.CharField(max_length=1000)),
                ('top_expertise', models.CharField(max_length=200)),
                ('My Resume', models.FileField(blank=True, upload_to='')),
                ('secondary_image', models.ImageField(blank=True, upload_to='portfolio/website/')),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='portfolio/project/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('text_body', models.TextField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('github', models.URLField(blank=True, null=True)),
                ('demo', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('YT', 'YoutTube'), ('TW', 'Twitter'), ('GH', 'GitHub'), ('MD', 'Medium'), ('LI', 'Medium'), ('EM', 'E-Mail')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TechnologiesStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfoliosettings')),
            ],
        ),
    ]
