# Generated by Django 3.1 on 2020-10-18 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_seoobject'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosettings',
            name='seo_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.seoobject'),
        ),
    ]
