# Generated by Django 3.1 on 2020-08-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosettings',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
