# Generated by Django 3.1 on 2020-10-18 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_seoobject'),
        ('portfolio', '0002_portfoliosettings_seo_object'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortfolioSettings',
            new_name='Setting',
        ),
    ]
