# Generated by Django 3.1 on 2020-08-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlink',
            name='name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
