# Generated by Django 3.1 on 2020-10-19 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0004_auto_20201018_2344'),
        ('portfolio', '0003_auto_20201018_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='seo_object',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='commons.seoobject'),
        ),
    ]
