# Generated by Django 3.1 on 2020-08-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_projectlink_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='text_body',
            field=models.TextField(null=True),
        ),
    ]
