# Generated by Django 3.1 on 2020-08-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_text_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='text_body',
            field=models.TextField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name='ProjectLink',
        ),
    ]
