# Generated by Django 3.1 on 2020-08-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20200823_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliosettings',
            name='about_me',
            field=models.CharField(max_length=1000),
        ),
    ]
